tasks:
  - init: yarn install && yarn run serve

vscode:
  extensions:
    - ahmadawais.shades-of-purple@6.12.0:phtipGVPrS5xO6knvBtr8A==
    - SonarSource.sonarlint-vscode@1.16.0:WqH3KkcnW+ruTGeBAU1vdQ==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - octref.vetur@0.24.0:FtNScOJHzSTxcNY6NB60Cg==
    - PKief.material-icon-theme@4.2.0:BMxWnfsRyjgBONLuFiMF4g==